fix-#461: Updated requirement file, backend & frontend .env.sample with Google auth, Redis installation

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,11 +1,16 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
-. "$(dirname -- "$0")/_/husky.sh"
+# Source the Husky script
+source "$(dirname -- "$0")/_/husky.sh"
 
-cd frontend
-echo [FRONTEND] Running the prettier format for you.
+# Run Prettier on frontend files
+cd frontend || { echo "Failed to change directory to frontend"; exit 1; }
+echo "[FRONTEND] Running the prettier format for you."
 npx lint-staged
 
-cd ../backend
-echo [BACKEND] Running the prettier format for you
+# Run Prettier on backend files
+cd ../backend || { echo "Failed to change directory to backend"; exit 1; }
+echo "[BACKEND] Running the prettier format for you."
 npx lint-staged
+
+
